<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>metrics</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- 提供 MetricRegistry、Gauge、Counter、Timer 等基础能力
         Metrics provides a powerful toolkit of ways to measure the behavior of critical components in your production environment. -->
        <dependency>
            <groupId>io.dropwizard.metrics5</groupId>
            <artifactId>metrics-core</artifactId>
            <version>5.0.8</version>
        </dependency>

        <!-- Run application-specific health checks -->
        <dependency>
            <groupId>io.dropwizard.metrics5</groupId>
            <artifactId>metrics-healthchecks</artifactId>
            <version>5.0.8</version>
        </dependency>

        <!-- 获取当前JVM的CPU、Memory、GC、Thread等运行时信息 -->
        <dependency>
            <groupId>io.dropwizard.metrics5</groupId>
            <artifactId>metrics-jvm</artifactId>
            <version>5.0.8</version>
        </dependency>

        <!-- 暴露并通过JMX来监控报告的指标
        A set of classes which allow you to report metrics via JMX. -->
        <dependency>
            <groupId>io.dropwizard.metrics5</groupId>
            <artifactId>metrics-jmx</artifactId>
            <version>5.0.8</version>
        </dependency>
    </dependencies>
</project>